server:
    port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    reactor.netty.http.client: DEBUG
    com.fursense.gateway: DEBUG

spring:
    application:
        name: gateway

    cloud:
        discovery:
            enabled: true
        gateway:
            routes:
                - id: auth
                  uri: "http://localhost:8090"
                  predicates:
                      - Path=/auth/**
                  filters:
                    - AuthFilter

                - id: notifications
                  uri: "http://localhost:8091"
                  predicates:
                      - Path=/notifications/**
                  filters:
                     - AuthFilter

                - id: user
                  uri: "http://localhost:8092"
                  predicates:
                    - Path=/user/**
                  filters:
                    - AuthFilter

                - id: pet
                  uri: "http://localhost:8093"
                  predicates:
                    - Path=/pet/**
                  filters:
                    - AuthFilter