server:
    port: ${PORT:8080}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    reactor.netty.http.client: DEBUG
    com.fursense.gateway: DEBUG

spring:
  application:
    name: gateway

    cloud:
        discovery:
            enabled: true
        gateway:
            routes:
                - id: auth
                  uri: ${AUTH_SERVICE_URL:http://localhost:8090}
                  predicates:
                      - Path=/auth/**
                  filters:
                    - AuthFilter

                - id: notifications
                  uri: ${NOTIFICATIONS_SERVICE_URL:http://localhost:8091}
                  predicates:
                      - Path=/notifications/**
                  filters:
                     - AuthFilter

                - id: user
                  uri: ${USER_SERVICE_URL:http://localhost:8092}
                  predicates:
                    - Path=/user/**
                  filters:
                    - AuthFilter

                - id: pet
                  uri: ${PET_SERVICE_URL:http://localhost:8093}
                  predicates:
                    - Path=/pet/**
                  filters:
                    - AuthFilter

                - id: pet
                  uri: ${CHATBOT_URL:http://localhost:4200/inference}
                  predicates:
                    - Path=/inference/**
                  filters:
                    - AuthFilter