server:
    port: 8080

spring:
    application:
        name: gateway

    cloud:
        discovery:
            enabled: true
        gateway:
            mvc:
                routes:
                    - id: users
                      uri: "http://localhost:8090"
                      predicates:
                          - Path=/user/**

                    - id: notifications
                      uri: "http://localhost:8091"
                      predicates:
                          - Path=/notifications/**